name: Python Setup

on:
  workflow_dispatch
jobs:
 python-setup:
   runs-on: ubuntu-latest
   steps:
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 4
    - name: print python version
      run: python -v
